### ISSUE TITLE
doesn't work with new version of oidcmsg

### ISSUE THREAD

**Issue by baszoetekouw** [IdentityPython/oidc-op#19]
With the latest version of oidmsg, this project fails to start

```
mrt 26 16:06:01 client oidc-op[4299]: Traceback (most recent call last):
mrt 26 16:06:01 client oidc-op[4299]:   File "/opt/oidc-op/flask_op/server.py", line 7, in <module>
mrt 26 16:06:01 client oidc-op[4299]:     import OpenSSL
mrt 26 16:06:01 client oidc-op[4299]: ModuleNotFoundError: No module named 'OpenSSL'
```
and after manually installing pyopenssl:
```
mrt 26 16:06:12 client oidc-op[4315]: Traceback (most recent call last):
mrt 26 16:06:12 client oidc-op[4315]:   File "/opt/oidc-op/flask_op/server.py", line 82, in <module>
mrt 26 16:06:12 client oidc-op[4315]:     main(args.config, args)
mrt 26 16:06:12 client oidc-op[4315]:   File "/opt/oidc-op/flask_op/server.py", line 57, in main
mrt 26 16:06:12 client oidc-op[4315]:     app = oidc_provider_init_app(config, 'oidc_op')
mrt 26 16:06:12 client oidc-op[4315]:   File "/opt/oidc-op/flask_op/application.py", line 47, in oidc_provider_init_app
mrt 26 16:06:12 client oidc-op[4315]:     app.endpoint_context = init_oidc_op_endpoints(app)
mrt 26 16:06:12 client oidc-op[4315]:   File "/opt/oidc-op/flask_op/application.py", line 21, in init_oidc_op_endpoints
mrt 26 16:06:12 client oidc-op[4315]:     endpoint_context = EndpointContext(_server_info_config, cwd=folder)
mrt 26 16:06:12 client oidc-op[4315]:   File "/opt/oidc-op/lib/python3.7/site-packages/oidcendpoint/endpoint_context.py", line 110, in __init__
mrt 26 16:06:12 client oidc-op[4315]:     self.add_boxes(
mrt 26 16:06:12 client oidc-op[4315]: AttributeError: 'EndpointContext' object has no attribute 'add_boxes'
```

Please use versioned requirements (i.e., `oidcmsg~=1.1.0`) to avoid this kind of breakages.

**Comment by rohe** [comment]
Yeah, you got trapped in a rewrite.
We're moving from having the JWTConnect modules accessing persistent storage to letting the front ends deal with in.
Give me another couple of days.
I'm almost done with the RP side will do the OP side there after.

**Comment by baszoetekouw** [comment]
Heh,  we're using it in a CI-setup to test our OIDC-login, so we will probably hit any transient issues that might occur in the dependencies.
For now, I've worked around it by installing fixed versions of the dependencies, but it would be great if you could tighten the dependencies in the mocole itself, too.

**Comment by rohe** [comment]
Sorry about this ! We will definitely tighten dependency specifications in the future.

**Comment by peppelinux** [comment]
@rohe 
add_boxes is deprecated (not used anymore) in develop branch, do we have to explain this here?
